### ISSUE TITLE
Quarto formatting not applied in README

### ISSUE THREAD

**Issue by etiennebacher** [IndrajeetPatil/awesome-r-pkgtools#10]
![image](https://user-images.githubusercontent.com/52219252/190486543-4062a68a-17b1-4912-adf7-743c116752a8.png)

**Comment by etiennebacher** [comment]
(works on the website though)

**Comment by IndrajeetPatil** [comment]
Yeah, I am aware of this, but not sure what to do here.

The only option I can think of is what I am doing in [kittyR package](https://github.com/IndrajeetPatil/kittyR):
Have `README.md` and `index.md` and knit the latter to HTML.

**Comment by etiennebacher** [comment]
Not sure either, but you're aware of this problem so I'll close this (just wanted to mention in case you didn't notice)

**Comment by IndrajeetPatil** [comment]
Let's keep it open. 

A lot of people might be landing on the README instead of the website, so definitely worth fixing sooner than later. 

I will try to see what I can do.

**Comment by IndrajeetPatil** [comment]
Using `gfm` format fixed this.
