### ISSUE TITLE
{packager} has been archived on CRAN

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [IndrajeetPatil/awesome-r-pkgtools#17]
https://github.com/IndrajeetPatil/awesome-r-pkgtools/blob/bb03c82cc96f7febbab819820a3d1ce4ff7ce3b9/README.qmd#LL44-L44C62

https://fvafrcu.gitlab.io/packager/

**Comment by IndrajeetPatil** [comment]
Thanks!
