### ISSUE TITLE
{packager} has been archived on CRAN

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [IndrajeetPatil/awesome-r-pkgtools#18]
https://github.com/IndrajeetPatil/awesome-r-pkgtools/blob/10e6ad57ece77049e02f2632e814239182b019ac/README.qmd#LL44C1-L44C62

Alternate location on GitLab https://gitlab.com/fvafrcu/packager

**Comment by IndrajeetPatil** [comment]
Thanks!
