### ISSUE TITLE
pkgcheck?

### ISSUE THREAD

**Issue by maelle** [IndrajeetPatil/awesome-r-pkgtools#3]
First of all, thanks for creating & maintaining this useful list! :sparkles: 

Then, here's a package suggestion: https://docs.ropensci.org/pkgcheck/ Although it has a specific goal (Check whether a package is ready for submission to rOpenSci’s peer review system.), its output could be more generally useful.

Cc @mpadge

**Comment by IndrajeetPatil** [comment]
Thanks for the suggestion!

Does that description look good?

**Comment by maelle** [comment]
Yes, thanks a ton! :pray:
