### ISSUE TITLE
inteRgrate

### ISSUE THREAD

**Issue by cosimameyer** [IndrajeetPatil/awesome-r-pkgtools#8]
It's still experimental but I think [{inteRgrate}](https://github.com/jumpingrivers/inteRgrate) could also be added to the list (it's similar to {goodpractice}) 😊

I like to use a couple of its [functions before submitting to CRAN](https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/r-package/#subsection5-6) :)

**Comment by IndrajeetPatil** [comment]
Looks awesome! Thanks for bringing it on my radar. 

Added it to the list :)
